/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    FontBlock: typeof import('./src/components/FontBlock.vue')['default']
    FontBlockList: typeof import('./src/components/FontBlockList.vue')['default']
    SelectFont: typeof import('./src/components/SelectFont.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
